# This file was generated by GoReleaser. DO NOT EDIT.
cask "coragent" do
  name "coragent"
  desc "CLI tool for managing Snowflake Cortex Agent deployments"
  homepage "https://github.com/jimatomo/cortex-agent-cli"
  version "0.19.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coragent"

  on_macos do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_amd64.tar.gz"
      sha256 "e9e4ee237ff352e10d68d770edabb6ff46078c63cfcba42c0469b3a43535493f"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_arm64.tar.gz"
      sha256 "ee0e7f1a006b64b778af7f84cadf7a46d110474971f6aabd69bec13f1b306538"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_amd64.tar.gz"
      sha256 "61812470f25e7310af2316446fc0728e4c68b8fa717ba150e16e32aebaa29ef6"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_arm64.tar.gz"
      sha256 "253784fd0f8d396a9cf3bd307912fa0ffdada7e4fa15905fad17d185fca2b7c9"
    end
  end

  # No zap stanza required
end
