# This file was generated by GoReleaser. DO NOT EDIT.
cask "coragent" do
  name "coragent"
  desc "CLI tool for managing Snowflake Cortex Agent deployments"
  homepage "https://github.com/jimatomo/cortex-agent-cli"
  version "0.23.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coragent"

  on_macos do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_amd64.tar.gz"
      sha256 "219332a4ccb4994e6c5852f00583cc22a45b9ed1cb7e216b2f564ec2351dbd13"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_arm64.tar.gz"
      sha256 "573b6250615d9de4307156281de5ba884ed458fc428838fc13a2b91481cceee7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_amd64.tar.gz"
      sha256 "6b992482ed6d31c332f09a4b1662831bf4b3c7a6c744f6393e9f954267919636"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_arm64.tar.gz"
      sha256 "22ba07ea49a86a65d499c2e891ed2b3a4b8eda83cd2e3921737cdcbde4da435c"
    end
  end

  # No zap stanza required
end
