# This file was generated by GoReleaser. DO NOT EDIT.
cask "coragent" do
  name "coragent"
  desc "CLI tool for managing Snowflake Cortex Agent deployments"
  homepage "https://github.com/jimatomo/cortex-agent-cli"
  version "0.24.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coragent"

  on_macos do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_amd64.tar.gz"
      sha256 "ee1cbdc395d024c95a62823512d1ecd2682f312179baf24790ff6a212507828e"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_darwin_arm64.tar.gz"
      sha256 "fd77743264ba507577d5df6d52cfb9d1309ddd27df9ec3580189c15f414d21ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_amd64.tar.gz"
      sha256 "9d3346e9b67b4d83ee89b874ed719161fb321425dd9fd4cacb601fcf7dfe6bd8"
    end
    on_arm do
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v#{version}/coragent_#{version}_linux_arm64.tar.gz"
      sha256 "2e817541817e354090deb7004fe14559fb9b3593d347b699c8eab6570cb4c2da"
    end
  end

  # No zap stanza required
end
