# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coragent < Formula
  desc "CLI tool for managing Snowflake Cortex Agent deployments"
  homepage "https://github.com/jimatomo/cortex-agent-cli"
  version "0.18.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v0.18.0/coragent_0.18.0_darwin_amd64.tar.gz"
      sha256 "14901d62c9a861adb26763a9f647cb264fee08029c45446af91c0bfaa3c6331b"

      define_method(:install) do
        bin.install "coragent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v0.18.0/coragent_0.18.0_darwin_arm64.tar.gz"
      sha256 "f94cc4ae376def990f4f0170e5719c3851ed8feefd4acbb7139eb62df4a46f0e"

      define_method(:install) do
        bin.install "coragent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v0.18.0/coragent_0.18.0_linux_amd64.tar.gz"
      sha256 "3d0a030d747cfcc63c37c883c9e7c034cf56f075465a493b1cd1d82c35275ad5"
      define_method(:install) do
        bin.install "coragent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimatomo/cortex-agent-cli/releases/download/v0.18.0/coragent_0.18.0_linux_arm64.tar.gz"
      sha256 "a44871e84a5afb2bb8c3bd2d8e39ab89859793a3ff4ca1e4b670d424c11db0f3"
      define_method(:install) do
        bin.install "coragent"
      end
    end
  end

  test do
    system "#{bin}/coragent", "--help"
  end
end
